install: install-apt install-system install-iptables install-sudo install-ssh install-user install-vim install-tor install-vpn install-dns install-www install-coin-dns

install-apt:
	./apt.rb

install-system:
	./system.rb

install-iptables:
	./iptables.rb

install-sudo:
	./sudo.rb

install-ssh:
	./ssh.rb

install-user:
	./user.rb

install-vim:
	./vim.rb

install-tor:
	./tor.rb

install-vpn:
	./vpn.rb

install-dns:
	./dns.rb

install-www:
	./www.rb

install-coin-dns:
	make -C coin-dns install
